// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ari-data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ari_2ddata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ari_2ddata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ari_2ddata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ari_2ddata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ari_2ddata_2eproto;
namespace ari {
class AriData;
struct AriDataDefaultTypeInternal;
extern AriDataDefaultTypeInternal _AriData_default_instance_;
class AriData_Ari;
struct AriData_AriDefaultTypeInternal;
extern AriData_AriDefaultTypeInternal _AriData_Ari_default_instance_;
}  // namespace ari
PROTOBUF_NAMESPACE_OPEN
template<> ::ari::AriData* Arena::CreateMaybeMessage<::ari::AriData>(Arena*);
template<> ::ari::AriData_Ari* Arena::CreateMaybeMessage<::ari::AriData_Ari>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ari {

// ===================================================================

class AriData_Ari final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ari.AriData.Ari) */ {
 public:
  inline AriData_Ari() : AriData_Ari(nullptr) {}
  ~AriData_Ari() override;
  explicit PROTOBUF_CONSTEXPR AriData_Ari(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AriData_Ari(const AriData_Ari& from);
  AriData_Ari(AriData_Ari&& from) noexcept
    : AriData_Ari() {
    *this = ::std::move(from);
  }

  inline AriData_Ari& operator=(const AriData_Ari& from) {
    CopyFrom(from);
    return *this;
  }
  inline AriData_Ari& operator=(AriData_Ari&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AriData_Ari& default_instance() {
    return *internal_default_instance();
  }
  static inline const AriData_Ari* internal_default_instance() {
    return reinterpret_cast<const AriData_Ari*>(
               &_AriData_Ari_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AriData_Ari& a, AriData_Ari& b) {
    a.Swap(&b);
  }
  inline void Swap(AriData_Ari* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AriData_Ari* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AriData_Ari* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AriData_Ari>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AriData_Ari& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AriData_Ari& from) {
    AriData_Ari::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AriData_Ari* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ari.AriData.Ari";
  }
  protected:
  explicit AriData_Ari(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHobbyFieldNumber = 3,
    kNameFieldNumber = 1,
    kAgeFieldNumber = 2,
  };
  // repeated string hobby = 3;
  int hobby_size() const;
  private:
  int _internal_hobby_size() const;
  public:
  void clear_hobby();
  const std::string& hobby(int index) const;
  std::string* mutable_hobby(int index);
  void set_hobby(int index, const std::string& value);
  void set_hobby(int index, std::string&& value);
  void set_hobby(int index, const char* value);
  void set_hobby(int index, const char* value, size_t size);
  std::string* add_hobby();
  void add_hobby(const std::string& value);
  void add_hobby(std::string&& value);
  void add_hobby(const char* value);
  void add_hobby(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& hobby() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_hobby();
  private:
  const std::string& _internal_hobby(int index) const;
  std::string* _internal_add_hobby();
  public:

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 age = 2;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ari.AriData.Ari)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> hobby_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t age_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ari_2ddata_2eproto;
};
// -------------------------------------------------------------------

class AriData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ari.AriData) */ {
 public:
  inline AriData() : AriData(nullptr) {}
  ~AriData() override;
  explicit PROTOBUF_CONSTEXPR AriData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AriData(const AriData& from);
  AriData(AriData&& from) noexcept
    : AriData() {
    *this = ::std::move(from);
  }

  inline AriData& operator=(const AriData& from) {
    CopyFrom(from);
    return *this;
  }
  inline AriData& operator=(AriData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AriData& default_instance() {
    return *internal_default_instance();
  }
  static inline const AriData* internal_default_instance() {
    return reinterpret_cast<const AriData*>(
               &_AriData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AriData& a, AriData& b) {
    a.Swap(&b);
  }
  inline void Swap(AriData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AriData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AriData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AriData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AriData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AriData& from) {
    AriData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AriData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ari.AriData";
  }
  protected:
  explicit AriData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef AriData_Ari Ari;

  // accessors -------------------------------------------------------

  enum : int {
    kAriFieldNumber = 1,
  };
  // repeated .ari.AriData.Ari ari = 1;
  int ari_size() const;
  private:
  int _internal_ari_size() const;
  public:
  void clear_ari();
  ::ari::AriData_Ari* mutable_ari(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ari::AriData_Ari >*
      mutable_ari();
  private:
  const ::ari::AriData_Ari& _internal_ari(int index) const;
  ::ari::AriData_Ari* _internal_add_ari();
  public:
  const ::ari::AriData_Ari& ari(int index) const;
  ::ari::AriData_Ari* add_ari();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ari::AriData_Ari >&
      ari() const;

  // @@protoc_insertion_point(class_scope:ari.AriData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ari::AriData_Ari > ari_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ari_2ddata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AriData_Ari

// string name = 1;
inline void AriData_Ari::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& AriData_Ari::name() const {
  // @@protoc_insertion_point(field_get:ari.AriData.Ari.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AriData_Ari::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ari.AriData.Ari.name)
}
inline std::string* AriData_Ari::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:ari.AriData.Ari.name)
  return _s;
}
inline const std::string& AriData_Ari::_internal_name() const {
  return _impl_.name_.Get();
}
inline void AriData_Ari::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* AriData_Ari::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* AriData_Ari::release_name() {
  // @@protoc_insertion_point(field_release:ari.AriData.Ari.name)
  return _impl_.name_.Release();
}
inline void AriData_Ari::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ari.AriData.Ari.name)
}

// int32 age = 2;
inline void AriData_Ari::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t AriData_Ari::_internal_age() const {
  return _impl_.age_;
}
inline int32_t AriData_Ari::age() const {
  // @@protoc_insertion_point(field_get:ari.AriData.Ari.age)
  return _internal_age();
}
inline void AriData_Ari::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void AriData_Ari::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:ari.AriData.Ari.age)
}

// repeated string hobby = 3;
inline int AriData_Ari::_internal_hobby_size() const {
  return _impl_.hobby_.size();
}
inline int AriData_Ari::hobby_size() const {
  return _internal_hobby_size();
}
inline void AriData_Ari::clear_hobby() {
  _impl_.hobby_.Clear();
}
inline std::string* AriData_Ari::add_hobby() {
  std::string* _s = _internal_add_hobby();
  // @@protoc_insertion_point(field_add_mutable:ari.AriData.Ari.hobby)
  return _s;
}
inline const std::string& AriData_Ari::_internal_hobby(int index) const {
  return _impl_.hobby_.Get(index);
}
inline const std::string& AriData_Ari::hobby(int index) const {
  // @@protoc_insertion_point(field_get:ari.AriData.Ari.hobby)
  return _internal_hobby(index);
}
inline std::string* AriData_Ari::mutable_hobby(int index) {
  // @@protoc_insertion_point(field_mutable:ari.AriData.Ari.hobby)
  return _impl_.hobby_.Mutable(index);
}
inline void AriData_Ari::set_hobby(int index, const std::string& value) {
  _impl_.hobby_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ari.AriData.Ari.hobby)
}
inline void AriData_Ari::set_hobby(int index, std::string&& value) {
  _impl_.hobby_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ari.AriData.Ari.hobby)
}
inline void AriData_Ari::set_hobby(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.hobby_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ari.AriData.Ari.hobby)
}
inline void AriData_Ari::set_hobby(int index, const char* value, size_t size) {
  _impl_.hobby_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ari.AriData.Ari.hobby)
}
inline std::string* AriData_Ari::_internal_add_hobby() {
  return _impl_.hobby_.Add();
}
inline void AriData_Ari::add_hobby(const std::string& value) {
  _impl_.hobby_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ari.AriData.Ari.hobby)
}
inline void AriData_Ari::add_hobby(std::string&& value) {
  _impl_.hobby_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ari.AriData.Ari.hobby)
}
inline void AriData_Ari::add_hobby(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.hobby_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ari.AriData.Ari.hobby)
}
inline void AriData_Ari::add_hobby(const char* value, size_t size) {
  _impl_.hobby_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ari.AriData.Ari.hobby)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
AriData_Ari::hobby() const {
  // @@protoc_insertion_point(field_list:ari.AriData.Ari.hobby)
  return _impl_.hobby_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
AriData_Ari::mutable_hobby() {
  // @@protoc_insertion_point(field_mutable_list:ari.AriData.Ari.hobby)
  return &_impl_.hobby_;
}

// -------------------------------------------------------------------

// AriData

// repeated .ari.AriData.Ari ari = 1;
inline int AriData::_internal_ari_size() const {
  return _impl_.ari_.size();
}
inline int AriData::ari_size() const {
  return _internal_ari_size();
}
inline void AriData::clear_ari() {
  _impl_.ari_.Clear();
}
inline ::ari::AriData_Ari* AriData::mutable_ari(int index) {
  // @@protoc_insertion_point(field_mutable:ari.AriData.ari)
  return _impl_.ari_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ari::AriData_Ari >*
AriData::mutable_ari() {
  // @@protoc_insertion_point(field_mutable_list:ari.AriData.ari)
  return &_impl_.ari_;
}
inline const ::ari::AriData_Ari& AriData::_internal_ari(int index) const {
  return _impl_.ari_.Get(index);
}
inline const ::ari::AriData_Ari& AriData::ari(int index) const {
  // @@protoc_insertion_point(field_get:ari.AriData.ari)
  return _internal_ari(index);
}
inline ::ari::AriData_Ari* AriData::_internal_add_ari() {
  return _impl_.ari_.Add();
}
inline ::ari::AriData_Ari* AriData::add_ari() {
  ::ari::AriData_Ari* _add = _internal_add_ari();
  // @@protoc_insertion_point(field_add:ari.AriData.ari)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ari::AriData_Ari >&
AriData::ari() const {
  // @@protoc_insertion_point(field_list:ari.AriData.ari)
  return _impl_.ari_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ari

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ari_2ddata_2eproto
